project:
  services:
    component_ping:
      name: component_ping
      version: v1
    component_pong:
      name: component_pong
      version: v1
    trellis-postapi:
      name: trellis-postapi
      version: v1
      options:
        http:
          postapi: "/v1"
          address: ":8080"
        gin_mode: debug
        apis:
          type: file ## default file | mysql
          file:
            trellis-test:
              api: trellis.ping
              service_name: component_ping
              service_version: v1
              topic: ping

