project:
    name: sample
    version: v1
    go:
        cgo: false
        version: "1.13"
    build:
        type: origin
        path: .
        delete_build_file: true
        flags: -mod vendor -a -tags netgo
        static: false
        ext_ldflags: []
        ldflags: |
            -X 'github.com/go-trellis/common/builder.ProgramName={{.Name}}'
            -X 'github.com/go-trellis/common/builder.ProgramVersion={{.Version}}'
            -X 'github.com/go-trellis/common/builder.CompilerVersion={{compiler}}'
            -X 'github.com/go-trellis/common/builder.Author={{ author }}@{{ hostname }}'
            -X 'github.com/go-trellis/common/builder.BuildTime={{datetime "2006-01-02 15:04:05"}}'
    services:
        trellis-postapi:
            url: github.com/go-trellis/trellis/service/api
        serviceA:
            url: github.com/go-trellis/trellis/examples/services
        serviceB:
            url: github.com/go-trellis/trellis/examples/services