project:
  services:
    -
      name: component_pong
      version: v1
      registry:
        name: grpc_test
        weight: 2
        ttl: 15s
        heartbeat: 10s
    -
      name: trellis-grpcserver
      version: v1
  registries:
    -
      name: grpc_test
      type: 1
      server_addr: 127.0.0.1:8081
      endpoints: ["127.0.0.1:2379"]
      secure: false
      timeout: 5s